server:
  port: 8080
  servlet:
    # session 失效时间1天
    session:
      timeout: 86400
    context-path: /api
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
  #  SpringBoot和swagger冲突
  mvc:
    path match:
      matching-strategy: ant_path_matcher
# redis配置  密码 null111
  redis:
    port: 6379
    host: localhost
    database: 1

mybatis:
  mapper-locations:UserMapper.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl